In [29]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator,SimpleImputer

In [31]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived'])
df

     Survived   Age     Fare
0           0  22.0   7.2500
1           1  38.0  71.2833
2           1  26.0   7.9250
3           1  35.0  53.1000
4           0  35.0   8.0500
..        ...   ...      ...
886         0  27.0  13.0000
887         1  19.0  30.0000
888         0   NaN  23.4500
889         1  26.0  30.0000
890         0  32.0   7.7500

[891 rows x 3 columns]

In [32]:
df.isnull().sum()

Survived      0
Age         177
Fare          0
dtype: int64

In [33]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [5]:
X_train['Age_imputed'] = X_train['Age']
X_test['Age_imputed'] = X_test['Age']

In [36]:
si = SimpleImputer(add_indicator=True)
X_train = si.fit_transform(X_train)
X_test = si.transform(X_test)

In [37]:
X_train

array([[ 40.        ,  27.7208    ,   0.        ],
       [  4.        ,  16.7       ,   0.        ],
       [ 47.        ,   9.        ,   0.        ],
       ...,
       [ 71.        ,  49.5042    ,   0.        ],
       [ 29.78590426, 221.7792    ,   1.        ],
       [ 29.78590426,  25.925     ,   1.        ]])

In [23]:
X_train['Age_imputed'][X_train['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_train['Age'].isnull().sum()).values
X_test['Age_imputed'][X_test['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_test['Age'].isnull().sum()).values

/tmp/ipykernel_2250/3090101260.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  X_train['Age_imputed'][X_train['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_train['Age'].isnull().sum()).values
/tmp/ipykernel_2250/3090101260.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  X_test['Age_imputed'][X_test['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_test['Age'].isnull().sum()).values

In [25]:
X_train['Age_imputed'].isnull().sum()

np.int64(0)

In [27]:
X_train

      Age      Fare  Age_imputed
30   40.0   27.7208         40.0
10    4.0   16.7000          4.0
873  47.0    9.0000         47.0
182   9.0   31.3875          9.0
876  20.0    9.8458         20.0
..    ...       ...          ...
534  30.0    8.6625         30.0
584   NaN    8.7125         35.0
493  71.0   49.5042         71.0
527   NaN  221.7792         36.0
168   NaN   25.9250         20.0

[712 rows x 3 columns]

In [38]:
!git clone https://github.com/ahmad-0313/Machine-Learning-Practice.git

Cloning into 'Machine-Learning-Practice'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 30 (delta 7), reused 16 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (30/30), 51.58 KiB | 2.87 MiB/s, done.
Resolving deltas: 100% (7/7), done.

In [39]:
%cd Machine-Learning-Practice

/content/Machine-Learning-Practice

In [41]:
!mkdir -p "Missing Value"

In [42]:
!cp /content/Random-sample-imputation.ipynb "Missing Value/"

cp: cannot stat '/content/Random-sample-imputation.ipynb': No such file or directory

In [43]:
!find /content -name "*.ipynb"

/content/Machine-Learning-Practice/Standarization/Standardization.ipynb
/content/Machine-Learning-Practice/normalization/Normalization.ipynb
/content/Machine-Learning-Practice/OrdinalLabelEncoding/Ordinal Label Encoding.ipynb
/content/Machine-Learning-Practice/Pipeline/Pipeline.ipynb
/content/Machine-Learning-Practice/ColumnTransformer/Columntransformer.ipynb

In [44]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [45]:
!find /content/drive/MyDrive -name "Random-sample-imputation.ipynb"

/content/drive/MyDrive/Colab Notebooks/Random-sample-imputation.ipynb

In [46]:
!cp "/content/drive/MyDrive/Random-sample-imputation.ipynb" "/content/Machine-Learning-Practice/Missing Value/"

cp: cannot stat '/content/drive/MyDrive/Random-sample-imputation.ipynb': No such file or directory