In [6]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer

In [2]:
df = pd.read_csv("covid_toy.csv")

In [3]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [7]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [4]:
from sklearn.model_selection import train_test_split

X = df.drop("has_covid", axis=1)
y = df["has_covid"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [9]:
# Columns
numerical_columns = ["fever"]
ordinal_columns = ["cough"]
onehot_columns = ["city", "gender"]

# Column Transformer
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            SimpleImputer(strategy="mean"),
            numerical_columns
        ),
        (
            "ordinal",
            OrdinalEncoder(
                categories=[["Mild", "Strong"]]
            ),
            ordinal_columns
        ),
        (
            "onehot",
            OneHotEncoder(handle_unknown="ignore"),
            onehot_columns
        )

    ],
     remainder="passthrough"
)

In [13]:
preprocessor.fit_transform(X_train).shape

(80, 9)

In [12]:
preprocessor.transform(X_test).shape

(20, 9)

In [14]:
%cd /content

/content

In [15]:
!git clone https://github.com/ahmad-0313/Machine-Learning-Practice.git

Cloning into 'Machine-Learning-Practice'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 17 (delta 3), reused 8 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (17/17), 15.86 KiB | 2.27 MiB/s, done.
Resolving deltas: 100% (3/3), done.

In [16]:
!git config --global user.name "Ahmad"
!git config --global user.email "1muhammadahmad0313@gmail.com"

In [17]:
!mkdir -p /content/Machine-Learning-Practice/ColumnTransformer

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!cp "/content/drive/MyDrive/Colab Notebooks/ColumnTransformer.ipynb" "/content/Machine-Learning-Practice/Columnt/"